services:
  # 1) MongoDB
  mongo:
    image: mongo:4.4
    container_name: fintrack-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

  # 2) Mongo Express
  mongo-express:
    image: mongo-express:latest
    container_name: fintrack-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
    depends_on:
      - mongo

  # 3) Go API
  server:
    image: golang:1.25.5
    container_name: fintrack-server
    working_dir: /app
    volumes:
      - ./server:/app
    command: sh -c "go mod download && go run ."
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://root:password@mongo:27017/?authSource=admin
      MONGODB_URI: mongodb://root:password@mongo:27017/?authSource=admin
      DB_NAME: fintrack_db

      ALLOWED_ORIGINS: https://fintrack.czhuang.dev,http://localhost:8080
      GIN_MODE: release
      PORT: "8080"
    depends_on:
      - mongo

  # 4) Frontend build (production)
  client:
    image: node:20
    container_name: fintrack-client
    working_dir: /app/client
    volumes:
      - ./:/app
      - /app/client/node_modules
    command: sh -c "npm install && npm run build"
    restart: "no"
