services:
  # 1. MongoDB 資料庫服務
  mongo:
    image: mongo:4.4  # ✨ 修改：鎖定 4.4 版本 (解決老舊 CPU AVX 崩潰問題)
    container_name: fintrack-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

  # 2. Mongo Express 圖形化管理介面
  mongo-express:
    image: mongo-express
    container_name: fintrack-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
    depends_on:
      - mongo

  # 3. Go API 服務
  server:
    image: golang:1.25.5
    container_name: fintrack-server
    working_dir: /app
    volumes:
      - ./server:/app
    command: sh -c "go mod download && go run ."
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  # 4. Vite 前端服務
  client:
    image: node:20
    container_name: fintrack-client
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules
    # ✨ 建議：明確指定 host 為 0.0.0.0 確保容器對外監聽
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    depends_on:
      - server